version: '3.8'
name: pizzacorp
include:
  - ../docker-compose.yml
services:
  devcontainer:
    extends:
      file: ../docker-compose.yml
      service: app
    profiles:
      - devcontainer
    build:
      target: devcontainer
    user: devcontainer
    command: sleep infinity
    volumes:
      - "../:/src/"
