version: '3.8'
name: pizzacorp
networks:
  # clone this repo: https://github.com/nalbury/example-localdev-network and launch it with docker compose e.g.
  # docker compose up -d
  # once running you can configure the network name in the .env file e.g. NETWORK_NAME=localdev
  localdev:
    external: true
  default: {}
services:
  postgres:
    networks:
      - ${NETWORK_NAME:-default}
    image: postgres:15-bookworm
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
  pgweb:
    depends_on:
      - postgres
    networks:
      - ${NETWORK_NAME:-default}
    image: ghcr.io/sosedoff/pgweb:0.14.2
    environment:
      - PGWEB_DATABASE_URL=$LOCAL_POSTGRES_URL
    labels:
      - "traefik.http.routers.examplefastapipg.rule=Host(`example-fastapi-pg.dev.local`)"
    ports:
      - 8081
